"""
Django settings for mysite project.
Generated by 'django-admin startproject' using Django 4.x.
For more information on this file, see:
https://docs.djangoproject.com/en/4.x/topics/settings/
For the full list of settings and their values, see:
https://docs.djangoproject.com/en/4.x/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: Keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w0wtmb1*$w9*+olet#qff#t&42#bv-)8=a+7g%7-l=9&csu+rz'

# SECURITY WARNING: Don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'channels',
    'myapp',
    'django.contrib.humanize', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'
ASGI_APPLICATION = 'mysite.asgi.application'

# Database configuration - SQLite for development, PostgreSQL for production
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation settings
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization settings
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files configuration (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type for Django models
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

# =============================================================================
# FIXED: Session & Cookie Settings for AJAX/SPA Compatibility
# =============================================================================

# Name of the cookie that stores the session ID
SESSION_COOKIE_NAME = 'sessionid'

# Controls whether cookies are sent with cross-site requests
# 'Lax' allows cookies on same-site AJAX requests while protecting against CSRF
SESSION_COOKIE_SAMESITE = 'Lax'

# Whether to use HTTPS for session cookies (set to True in production with HTTPS)
SESSION_COOKIE_SECURE = False

# Whether JavaScript can access the session cookie (True = more secure)
SESSION_COOKIE_HTTPONLY = True

# Save session to database on every request to ensure real-time updates
SESSION_SAVE_EVERY_REQUEST = True

# Whether session expires when browser is closed
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Session lifetime in seconds (2 weeks = 1209600 seconds)
SESSION_COOKIE_AGE = 1209600

# CSRF cookie settings for AJAX requests
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False
# Allow JavaScript to read CSRF token for AJAX requests
CSRF_COOKIE_HTTPONLY = False

# Email configuration - Console backend for development (emails print to terminal)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'Easy Transport <noreply@easytransport.com>'

# Channel layers configuration for WebSocket support (Chat system)
# Using in-memory backend for development, Redis for production
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Use session authentication for web interface
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# API documentation settings for drf-spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'Easy Transport API',
    'DESCRIPTION': 'Smart Institutional Transportation Management System API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
# Additional settings for logging, caching, etc. can be added here as needed for testing documented information updates.

"""
SESSION_SAVE_EVERY_REQUEST = True - Saves session on every request
SESSION_COOKIE_SAMESITE = 'Lax' - Allows cookies on same-site AJAX
CSRF_COOKIE_HTTPONLY = False - Allows JS to read CSRF token
"""