# Generated by Django 6.0.4 on 2026-04-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='institution_id',
            field=models.CharField(max_length=100),
        ),
    ]
