# Generated by Django 6.0.4 on 2026-05-09 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_driver_trip_tripstop_vehicleissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_chat_rooms', to='myapp.driver'),
        ),
    ]
