# Generated by Django 6.0.4 on 2026-05-12 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_booking_admin_remarks_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedules', to='myapp.driver'),
        ),
        migrations.AddField(
            model_name='trip',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='myapp.schedule'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='myapp.bus'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='myapp.route'),
        ),
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('driver', 'travel_date', 'departure_time')},
        ),
    ]
