# Generated by Django 6.0.4 on 2026-04-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_schedule_available_seats_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
