# Generated by Django 6.0.4 on 2026-05-03 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_booking_options_alter_bus_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='number_of_seats',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='passenger_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='passenger_phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat_numbers',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='last_maintenance',
        ),
        migrations.RemoveField(
            model_name='route',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='institution_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('sslcommerz', 'SSLCommerz'), ('cash', 'Cash')], default='bkash', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(default='bkash', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('admin', 'Admin'), ('driver', 'Driver')], default='student', max_length=20),
        ),
    ]
