# Generated by Django 6.0.4 on 2026-05-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_booking_options_alter_bus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='institution_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
