[pytest]
addopts = 
    --html=reports/test_report.html 
    --self-contained-html
    -v
    --tb=short
    -s
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
base_url = http://127.0.0.1:8000